### ISSUE TITLE
Running ox-ctrl-volt with LS2088

### ISSUE THREAD

**Issue by sooyun802** [DFC-OpenSource/ox-ctrl#13]
When running ox-ctrl-volt with LS2088, a segmentation fault occurs.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/26572842/44962460-e0035680-af5b-11e8-80c5-e22bfaa89f38.png">

```
root@ls2088aissd:/mnt# gdb ox-ctrl-volt
GNU gdb (GDB) 7.10.1.20160210-cvs
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-fsl-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ox-ctrl-volt...done.
(gdb) r start
Starting program: /mnt/ox-ctrl-volt start
warning: File "/lib/libthread_db-1.0.so" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load".
To enable execution of this file add
        add-auto-load-safe-path /lib/libthread_db-1.0.so
line to your configuration file "/home/root/.gdbinit".
To completely disable this security protection add
        set auto-load safe-path /
line to your configuration file "/home/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
        info "(gdb)Auto-loading safe path"
warning: Unable to find libthread_db matching inferior's thread library, thread debugging will not be available.
OX Controller 1.4.0 - The Lonely Dragon
 Starting...
[New LWP 1401]
[New LWP 1402]
[New LWP 1403]
[New LWP 1404]
[New LWP 1405]
[New LWP 1406]
[New LWP 1407]
[New LWP 1408]
[New LWP 1409]
[New LWP 1410]
[New LWP 1411]
[New LWP 1412]
[New LWP 1413]
[New LWP 1414]
[New LWP 1415]
[New LWP 1416]
[New LWP 1417]
 [volt: Volatile memory usage: 2063 Mb]
[New LWP 1418]
[LWP 1417 exited]
[New LWP 1419]
[New LWP 1420]
[New LWP 1421]
[New LWP 1422]
[New LWP 1423]
[New LWP 1424]
[New LWP 1425]
[New LWP 1426]
[New LWP 1427]
[New LWP 1428]
[New LWP 1429]
[New LWP 1430]
[New LWP 1431]
[New LWP 1432]
[New LWP 1433]
[New LWP 1434]

Program received signal SIGSEGV, Segmentation fault.
[Switching to LWP 1401]
0x0000ffffb7e73568 in memcpy () from /lib/libc.so.6
(gdb) bt
#0  0x0000ffffb7e73568 in memcpy () from /lib/libc.so.6
#1  0x00000000004124a8 in volt_nand_dma (paddr=0x411, buf=0x8104eff0, sz=16448, dir=1 '\001') at mmgr/volt/volt.c:389
#2  0x00000000004125b0 in volt_process_io (cmd=0x815b7690) at mmgr/volt/volt.c:414
#3  0x00000000004126a0 in volt_execute_io (req=0x815512c0) at mmgr/volt/volt.c:448
#4  0x0000000000406430 in ox_mq_sq_thread (arg=0x8154fff0) at ox-mq.c:327
#5  0x0000ffffb7f97e10 in ?? () from /lib/libpthread.so.0
#6  0x0000ffffb7fb7000 in ?? () from /lib/libpthread.so.0
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

Programs ox-ctrl and ox-ctrl-test do not seem to be working as well.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/26572842/44962462-f4475380-af5b-11e8-9ecb-5d359a092399.png">

I've used the latest release files (v1.4.0) and set CC as the following.
```
CC = /home/xxx/ISSD-SDK-V1.1-20170731-yocto/build_ls2088aissd/tmp/sysroots/x86_64-linux/usr/bin/aarch64-fsl-linux/aarch64-fsl-linux-gcc --sysroot=/home/xxx/ISSD-SDK-V1.1-20170731-yocto/build_ls2088aissd/tmp/sysroots/ls2088aissd
```

Could it be because of the DFC I'm using or how I've set the CC or anything else?

**Comment by ivpi** [comment]
Hi,

The problem happened because this version of OX does not support the LS2088 board. It will work only in the LS2085 with FPGA 03.01.00.

The LS2088 has issues with the host connection, the Segfault is due a copy to a host memory that does not exist.

OX 2.0 will support the LS2088, however the connection will be over fabrics instead of PCIe. 

For now, you have to use the LS2085.

Ivan
